
#####sELECTOR METHOD GP2 INDIVIDUAL

#let us select SL values for one individual  

SL_GP2 <- foo5[foo5$dt < 7500 & foo5$individual.local.identifier == "GP2", 'SL']
SL_GP2 <- na.omit(SL_GP2)

# install.packages('Segmentor3IsBack')  
require('Segmentor3IsBack')

# Exact change-point algorithm for the segmentation of profiles according to the log-likelihood criterion for 5 possible models: 
# Poisson, Gaussian homoscedastic, negative binomial, Gaussian with constant mean and Exponential.
# for exemplification, we use the default Poisson one
# see: ?Segmentor3IsBack

##  Los breakpoint me ayuda por definicion para segmentar los pasos de los bichos 
#por ejemplo me ayuda a definir , por cuantos segmentos podre realizar los pasos de los animales.
?Segmentor
res100 <- Segmentor(data=as.numeric(SL_GP2),Kmax=100)
str(res100)
breaks100 <- as.numeric(res100@breaks[100,])
plot(1:100,res100@likelihood[,1])  


res20 <- Segmentor(data=as.numeric(SL_GP2),Kmax=20)
str(res20)
breaks20 <- as.numeric(res20@breaks[20,])
plot(1:20,res20@likelihood[,1])



# plot the time series and break points

plot(1:length(SL_GP2), log(SL_GP2 + 1), type = "l")
points((1:length(SL_GP2))[breaks20], (log(SL_GP2 + 1))[breaks20], col=2, pch=19,cex=1.5)




# think about what you actually might want to obtain from this and compare to previous GAM model, as well as observed pattern in plotted data


################################################################  

##########################################################################################################################################################################
# Movement Path Segmentation - method of Lavielle 

# Lavielle method: method to identify breaks in timeseries (e.g. of speed)
# assumes data generated by process: Yi = µi + si ei
# can assume that only mean, or standard deviation, or both changes between segments, and assess adequacy of these assumptions using three contrast functions
# need to specify a minimum number of locations for each segment
# the number K of partitions to achieve are determined by a contrast function in relation to K, to find Kopt
# method is implemented in function lavielle()

# load library if needed
# library(adehabitatLT)

# continue with the ltraj object: Elktraj
# convert to ltraj object (type II) if needed

# Elktraj <- as.ltraj(xy = elkDataSrtB[,c("utm.easting","utm.northing")], date = elkDataSrtB$DateTime, id = elkDataSrtB$individual.local.identifier)


l1 <- lavielle(na.omit(Elktraj[3][[1]]$dist), Lmin=3, Kmax=20, type="mean")
l1
str(l1)


# These functions allow to perform a non-parametric segmentation of a time series using the penalized contrast method of Lavielle (1999, 2005). 
# The function lavielle computes the contrast matrix (i.e., the matrix used to segment the series) either from a series of observations or from 
# an animal trajectory. The function chooseseg can be used to estimate the number of segments building up the trajectory. The function findpath 
# can be used to find the limits of the segments (see Details).


chooseseg(l1) # see also plot --> the Jk value becomes much less negative starting with K=12. To check, redo with higher K

# we can visualize the segmentation

fp <- findpath(l1, 20)

#######################################################################

Elktraj
elkGP2 <- Elktraj[3]
resGP2 <- residenceTime(elkGP2, radius = 1000, maxt=6, units="hour") ##MAXT SWON LAS HORAS EN LAS QUE VUELVE 
plot(resGP2)

# maybe lets increase to 2km and 12 hours
resGP2 <- residenceTime(elkGP2, radius = 2000, maxt=12, units="hour")
plot(resGP2)

resGP2 <- residenceTime(elkGP2, radius = 4000, maxt=24, units="hour")
plot(resGP2)

?lavielle

names(resGP2)
head(resGP2$GP2)

lgp2 <- lavielle(na.omit(resGP2$GP2[, "RT.1000"]), Lmin=3, Kmax=20, type="mean")

lgp2 <- lavielle(na.omit(resGP2$GP2[, "RT.1000"]), Lmin=3, Kmax=50, type="mean")

lgp2
str(lgp2)
chooseseg(lgp2)

lgp3 <- lavielle(na.omit(resGP2$GP2[, "RT.1000"]), Lmin=3, Kmax=10, type="mean")

lgp3
str(lgp3)
chooseseg(lgp3)

fp <- findpath(lgp3, 6)

